export const REGISTER_USER_REQUEST ="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS ="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE ="REGISTER_USER_FAILURE";

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const TOGGLE_BETWEEN_REGISTER_LOGIN ="TOGGLE_BETWEEN_REGISTER_LOGIN";