export const REGISTER_USER_REQUEST ="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS ="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE ="REGISTER_USER_FAILURE";

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const TOGGLE_BETWEEN_REGISTER_LOGIN ="TOGGLE_BETWEEN_REGISTER_LOGIN";

export const LOGIN_WITH_GOOGLE ="LOGIN_WITH_GOOGLE";
export const LOGIN_WITH_FACEBOOK ="LOGIN_WITH_FACEBOOK";

export const REGISTER_REQUEST_WITH_GOOGLE ="REGISTER_REQUEST_WITH_GOOGLE";
export const REGISTER_REQUEST_WITH_FACEBOOK ="REGISTER_REQUEST_WITH_FACEBOOK";

export const REGISTER_WITH_GOOGLE_SUCCESS ="REGISTER_WITH_GOOGLE_SUCCESS";
export const REGISTER_WITH_FACEBOOK_SUCCESS ="REGISTER_WITH_FACEBOOK_SUCCESS";

export const LOG_OUT ="LOG_OUT";
