export const GET_DATA_BY_CATEGORY_REQUEST = "GET_DATA_BY_CATEGORY_REQUEST";
export const GET_DATA_BY_CATEGORY_SUCCESS = "GET_DATA_BY_CATEGORY_SUCCESS";
export const GET_DATA_BY_CATEGORY_FAILURE = "GET_DATA_BY_CATEGORY_FAILURE";


