//Getting data from API

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
export const GET_DATA_SUCCESS_ONE = "GET_DATA_SUCCESS_ONE";
export const GET_DATA_SUCCESS_TWO = "GET_DATA_SUCCESS_TWO";
export const GET_DATA_SUCCESS_THREE = "GET_DATA_SUCCESS_THREE";
export const GET_DATA_SUCCESS_FOUR = "GET_DATA_SUCCESS_FOUR";
export const GET_DATA_SUCCESS_FIVE = "GET_DATA_SUCCESS_FIVE";
export const GET_DATA_SUCCESS_SIX = "GET_DATA_SUCCESS_SIX";
export const GET_DATA_SUCCESS_SEVEN = "GET_DATA_SUCCESS_SEVEN";
export const GET_DATA_SUCCESS_EIGHT = "GET_DATA_SUCCESS_EIGHT";
export const GET_DATA_REQUEST_COMPLETE = "GET_DATA_REQUEST_COMPLETE";
